prefix = "."
stop-words = "stopwords.txt"

dataset = "documents"
corpus = "line.toml"
index = "idx"

query-judgements = "qrels.txt"


[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "CampusWireHeading_Queries.txt"
query-id-start = 1

